### ISSUE TITLE
Good Article !!!!!!

### ISSUE THREAD

**Issue by karpra** [msanand/feedback#1]
I had similar problems of trying to start choosing a platform to blog about technology , finally i tried wordpress , tumblr etc.. but jekyll hsa been pretty neat. I like the idea of able to run out own blog site with minimal intervention , also github pages is very good. Thanks for the motivating article .. I jump started my journey into setting up my blog.

**Comment by msanand** [comment]
Thanks @karpra. Good luck with your blog!
