### ISSUE TITLE
Issue with lanyon: Sidebar won't work properly in cellphone

### ISSUE THREAD

**Issue by hbahamonde** [msanand/feedback#4]
Hey Anand, hope all is well. I was looking at your website and it's really great. I'm using the same theme, but somehow, it does't work properly when loaded from my mobile device (iPhone/Safari). Yours does. **www.hectorbahamonde.com** works fine from my computer, but the side button won't close the sidebar when loaded from my phone. One has to kind of click on it many times, so it closes it but at random.

Did you do anything special on it, or did I just screw up a line? 

If you can give me a hand, it would be very much appreciated! Thanks.

**Comment by msanand** [comment]
hi @hbahamonde , thanks and sorry for the late response. I don't remember doing anything special for the menu to work. But I see that its already working for you. Not sure if you had to tweak something to fix it.
